using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class BirdsInformation : MonoBehaviour
{
    public BirdsAnimations birdsAnimations;
    public ScrollRect myScrollRect;
    public Sprite[] birdPhotos;
    public Sprite[] maps;

    public Image photo;
    public Image map;
    public Text description;
    public GameObject descriptionContainer;

    int nbird;

    private string[] birdsInformationTextEs = new string[] 
        {"NOMBRE CIENTÍFICO\nRamphastos sulfuratus.\n\nDESCRIPCIÓN\nEs un ave de plumaje negro contrastado con el amarillo intenso del cuello y parte del pecho; posee un gran pico de 16 cm de largo. Su nombre se debe a que tiene un flamante pico con los colores del arco iris.\nEs el ave nacional de Belice, se alimentan de frutas, invertebrados y reptiles pequeños.\n\nOTROS NOMBRES\nTucán piquiverde, tucán pico de canoa."
        ,"NOMBRE CIENTÍFICO\nCharadrius alexandrinus.\n\nDESCRIPCIÓN\nEs una especie de ave característica de las playas, arenales costeros, saladares y lagunas.Miden unos 15-17 cm de largo y 42-45 de envergadura.\nEn áreas de interior se alimenta fundamentalmente de insectos adultos y larvas de escarabajos, moscas, hormigas e invertebrados acuáticos, mientras que en zonas de agua salada su principal alimento lo constituyen diferentes crustáceos, lombrices y moluscos.\n\nOTROS NOMBRES\nChorlito alejandrino (México), frailecillo blanco (Cuba), frailecito (Venezuela) o playero corredor (República Dominicana)."
        ,"NOMBRE CIENTÍFICO\nCacatua galerita.\n\nDESCRIPCIÓN\nEs una cacatúa grande, mide unos 50 cm y pesa alrededor de 900 g. Las hembras son ligeramente mayores. Su plumaje es de color blanco, con una cresta amarilla de largas plumas.\nSe dieta está conformada principalmente por semillas, suelen alimentarse en el suelo, con algunos individuos posados en los árboles para vigilar y alertar de las posibles amenazas.\n\nOTROS NOMBRES\nCacatúa de moño amarillo."
        ,"NOMBRE CIENTÍFICO\nRupicola peruvianus.\n\nDESCRIPCIÓN\nEs un ave nativa de la región andino - amazónica del noroeste y oeste de América del Sur, es considerado el ave símbolo de Perú.\nSe alimenta de una gran cantidad de frutos silvestres(secos).\n\nOTROS NOMBRES\nGallito de las rocas de los andes (Perú), gallito de las sierras (Venezuela), gallo de la peña andino (Ecuador), gallito o gallo de roca andino (Colombia), gallito de monte, berreador o chaperón."
        ,"NOMBRE CIENTÍFICO\nAra macao.\n\nDESCRIPCIÓN\nEs una de las nueve especies existentes del género Ara, del cual es una de las de mayor tamaño, pues llega a alcanzar 90,7 cm de longitud y 1 kg de peso. Se distingue por su plumaje de colores vivos, que es principalmente rojo escarlata, complementado con algunas plumas azules y amarillas con verde que inician desde las alas hasta su cola.\nSu dieta se compone predominantemente de semillas, aunque también consume frutas, néctar, insectos o las flores, las hojas y el tallo de ciertas plantas\n\nOTROS NOMBRES\nGuacamayo escarlata, guacamayo bandera, guacamaya roja, papagayo rojo, paraba bandera, Lapa colorada y muchos más."
        ,"NOMBRE CIENTÍFICO\nMomotus aequatorialis\n\nDESCRIPCIÓN\nEste ave mide 48 cm y pesa entre 123 y 176 g. Habita en bosques húmedos de montaña y una gran variedad de hábitats como cultivos, áreas abiertas con árboles dispersos, jardines, bordes y claros de bosque.\nSe alimenta de insectos grandes, escarabajos, orugas, lagartos, ranas y ratones…\nGeneralmente permanece solitario o en parejas en el nivel medio o bajo de la vegetación. Se percha silenciosamente y en momentos de alarma se queda quieto y mueve su cola como un péndulo.\n\nOTROS NOMBRES\nMomoto serrano,  momoto corona azul, burgo montañés, barranquero, soledad, barranquillo de montaña, relojero montañés."
        ,"NOMBRE CIENTÍFICO\nSemnornis ramphastinus.\n\nDESCRIPCIÓN\nEs un barbudo robusto, de tamaño medio con un peso entre 80 y 115 gramos. Son aves muy coloridas de una morfología inconfundible. Se caracterizan por tener un pico muy robusto con maxila amarilla y mandíbula verde clara, ambos con puntas negras.\nSon aves frugívoras, se alimentan de una variedad de frutas, en especial de los amentos de las Cecropias aunque tienen en su dieta un componente de alrededor del 20% de insectos, además de néctar, savia y pétalos de flores.\n\nOTROS NOMBRES\nTucán cabezón, capitán tucán, tucán barbudo, compás, yumbo."
        ,"NOMBRE CIENTÍFICO\nPteroglossus torquatus.\n\nDESCRIPCIÓN\nComo otros tucanes, el tucancillo collarejo es muy colorido y posee un gran pico. Los adultos comúnmente miden 41 cm de largo y llegan a pesar 230 gr.\nEl tucancillo collarejo es un residente común en las selvas de tierras bajas y bosques un poco abiertos. Parvadas pequeñas, usualmente conformadas por 6-15 aves, atraviesan el bosque en vuelo rápido y directo.\nEsta especie arborícola es principalmente frugívora, pero también consume insectos, pequeños reptiles, huevos de aves y otras presas pequeñas.\n\nOTROS NOMBRES\nTucancillo collarejo o arasarí acollarado"
        ,"NOMBRE CIENTÍFICO\nChlorochrysa nitidissima.\n\nDESCRIPCIÓN\nLa tángara multicolor es endémica del interior de los bosques subandinos de las cordilleras Central y Occidental de los Andes de Colombia. Mide entre 12 a 14 cm de longitud total del cuerpo. La cola mide de 4 a 5 cm, y la envergadura de las alas de 6 a 7 cm.\nEsta especie es considerada poco común y local en sus hábitats naturales: los bosques húmedos de montaña y clareras adyacentes, Prefiere bosques maduros, sin embargo también utiliza bosques secundarios y bordes de bosque.\nUsualmente busca insectos debajo de las hojas, colgándose de las ramas más externas de los árboles de forma acrobática. Numerosos registros indican que además se alimenta de frutos maduros."
        ,"NOMBRE CIENTÍFICO\nEubucco bourcierii.\n\nDESCRIPCIÓN\nMide en promedio 15 cm de longitud y pesa 35 g. Vive principalmente en el bosque húmedo y también en los matorrales aledaños, entre los 400 y 1.850 m de altitud, efectuando migraciones altitudinales estacionales.\nSe alimenta de insectos, arácnidos y frutas. Hacen sus nidos en huecos de troncos, a una altura de 0,6 a 2,5 m.\n\nOTROS NOMBRES\nCapitán de cabeza roja, cabezón cabecirrojo, barbudo cabecirrojo."
        ,"NOMBRE CIENTÍFICO\nAmazona ochrocephala.\n\nDESCRIPCIÓN\nEs una especie de loro, nativa de casi toda América con subespecies desde el sur de México a Perú, Brasil, Bolivia, Colombia y Venezuela. Mide 35-37 cm de longitud.\nSe los halla normalmente de a pares, más que en bandadas. Comen frutos, nueces, semillas, bayas, cacahuetes, etc."
        ,"NOMBRE CIENTÍFICO\nAra ararauna.\n\nDESCRIPCIÓN\nMide entre 76 y 86 cm de largo y pesa de 900 a 1500 g. Viven en hábitats variados que van desde bosque húmedo tropical, selva tropical a sabana seca.\nSe alimenta principalmente de frutos, semillas y néctar de algunas flores.\n\nOTROS NOMBRES\nGuacamayo amarillo azulado, papagayo amarillo, paraba azul amarillo."
        ,"NOMBRE CIENTÍFICO\nPyrocephalus rubinus.\n\nDESCRIPCIÓN\nEs un ave pequeña en la que el macho presenta un color rojo brillante y alas, cola y antifaz oscuro mientras la hembra es de color pardo. Vive en bosques xerófilos, sabanas, praderas, áreas rurales, etc.\nSe alimenta de insectos.\n\nOTROS NOMBRES\nChurrinche, atrapamoscas pechirojo, mosquero cardenal, capiturrín, saca-tu-real, chapaturrín."
        ,"NOMBRE CIENTÍFICO\nBubo virginianus.\n\nDESCRIPCIÓN\nEs un ave extremadamente adaptable que vive en una gran extensión de territorio y es el búho más ampliamente distribuido en las Américas. Habita una gran variedad de hábitats, áreas abiertas asociadas a bosques y cuerpos de agua, bosques tropicales, templados, pantanosos y de coníferas, además manglares, desiertos y páramos, y asimismo vegetación secundaria y parques.\nAl igual que otras especies de búhos, el búho americano es capaz de realizar un 'vuelo silencioso', que es la forma en que los búhos vuelan sin hacer casi ningún ruido perceptible, a pesar de su gran tamaño.\nSe alimenta de pequeños mamíferos, reptiles e incluso peces. Se ha reproducido en cautiverio. Se utilizó y se sigue utilizando para cetrería.\n\nOTROS NOMBRES\nBúho americano, búho tigre, búho real americano."
        ,"NOMBRE CIENTÍFICO\nTyto alba.\n\nDESCRIPCIÓN\nEs una de las aves más ampliamente distribuidas del mundo, pudiendo encontrarse en casi todo el planeta, con excepción de regiones polares o desérticas.\nEs un ave mediana; mide de 33 a 35 cm de longitud y sus alas poseen una envergadura de 80 a 95 cm, con un peso medio para los adultos de 350 g, y sin diferencia aparente entre sexos.\nSe alimentan principalmente de pequeños roedores, especialmente ratones y musarañas, aunque también caza pequeños pájaros, insectos y, en menor medida, anfibios y reptiles.\n\nOTROS NOMBRES\nLechuza común, lechuza blanca."
        ,"NOMBRE CIENTÍFICO\nBubo scandiacus.\n\nDESCRIPCIÓN\nEs un búho bastante reconocible que habita la tundra de Asia, Norteamérica y Europa. El búho nival es ave oficial de la provincia canadiense de Quebec.\nEsta ave de ojos dorados y pico negro mide 53 a 65 cm de longitud con 120 a 150 cm de envergadura. Además, estos búhos pueden pesar entre 1,6 y 3 kg.\nLa dieta del búho nival se basa principalmente en lemmings y otros pequeños roedores, además de algunas aves, entre estas están: la perdiz nival, patos, gansos, faisanes, urogallos, fochas, gaviotas e incluso otras aves rapaces.\n\nOTROS NOMBRES\nBúho de las nieves, búho del Ártico, gran búho blanco."
        ,"NOMBRE CIENTÍFICO\nCorvus corax.\n\nDESCRIPCIÓN\nEsta ave está presente en todo el hemisferio septentrional, es la especie de córvido con la mayor superficie de distribución. Mide entre 52 y 69 cm de longitud y su peso varía de 0,69 a 1,7 kg.\nEl cuervo grande coexiste con los humanos desde hace millares de años y en algunas regiones es tan abundante que se considera una especie nociva. Una parte de su éxito se debe a su régimen omnívoro; el cuervo grande es extremadamente oportunista, alimentándose de carroñas, de insectos, de residuos alimentarios, de cereales, de frutas y de pequeños animales.\n\nOTROS NOMBRES\nCuervo grande."
        ,"NOMBRE CIENTÍFICO\nCardellina canadensis.\n\nDESCRIPCIÓN\nEsta ave anida en Norteamérica e inverna principalmente en el norte de Suramérica. Mide entre 12 y 13 cm de longitud. Habita bosques densos, húmedos y semihúmedos, a bajas o medianas altitudes.\nSe alimenta principalmente de insectos, sobre la vegetación, en el suelo, o en el vuelo.\n\nOTROS NOMBRES\nBijirita del Canadá, chipe de collar."
        ,"NOMBRE CIENTÍFICO\nParoaria gularis.\n\nDESCRIPCIÓN\nEsta ave es nativa de la cuenca amazónica y del escudo guayanés en América del Sur. En promedio mide 16,5 cm de longitud y pesa 22 g. Es bastante visible, se encuentra generalmente en parejas o en pequeños grupos familiares, cerca de orillas, frecuentemente en el suelo barriento y algunas veces sobre la vegetación flotante.\nSe alimenta de insectos, frutas y de granos como el arroz.\n\nOTROS NOMBRES\ncardenal bandera alemana, cardenal pantanero, cardenal gorrirrojo, cardenal de gorro rojo."
        ,"NOMBRE CIENTÍFICO\nCoereba flaveola.\n\nDESCRIPCIÓN\nEsta especie ocurre en casi cualquier área semi-abierta, arbustiva o de bordes de bosque, tanto en regiones húmedas como bastante secas. Mide unos 11 cm de longitud.\nSe alimenta principalmente de néctar; también de pequeños frutos y bayas y unos pocos insectos.\n\nOTROS NOMBRES\nReinita, reinita común, mielero, azucarero, reinita mielera, cigüita común, mielero cejiblanco entre otros."
        ,"NOMBRE CIENTÍFICO\nColumbidae.\n\nDESCRIPCIÓN\nLas colúmbidas se distribuyen por todo el mundo, excepto la Antártida y el Ártico. Son aves dotadas de gran inteligencia (si se las compara con otras aves).\nAparte de tener un gran sentido de la orientación, la paloma es una de las aves que más rápido vuela: alcanza los 56 km/h.8 También caracteriza a las palomas su agudísimo sentido de la vista: entre finales de los años 70 y principios de los 80 la Guardia Costera de Estados Unidos desarrolló un sistema experimental de rescate con palomas adiestradas en reconocer colores brillantes.\nLa paloma fue utilizada tanto en la Primera Guerra Mundial como en la Segunda Guerra Mundial, especialmente por las fuerzas australianas, francesas, alemanas, estadounidenses y del Reino Unido. También fueron galardonadas con varios laureles por su servicio."
        ,"NOMBRE CIENTÍFICO\nColumbidae.\n\nDESCRIPCIÓN\nLa paloma blanca se encuentra repartida por todo el mundo. Generalmente son muy vistas en las plazas y hasta las podemos encontrar en los sitios menos esperados. En cualquier ciudad o calle, en cualquier parque o avenida. No hay un sitio específico de reunión para este tipo de ave.\nEs importante saber lo que representa una paloma blanca, la cual desde hace mucho tiempo ha sido símbolo de paz. La paloma blanca fue el símbolo para la Campaña de Desarme Nuclear en 1958, y hoy en día se le reconoce como el emblema universal de la paz."
        ,"NOMBRE CIENTÍFICO\nThraupis episcopus\n\nDESCRIPCIÓN\nEsta especie, ampliamente diseminada, es generalmente común en áreas semi-abiertas y urbanizadas, y en una variedad de hábitats forestales, tanto de regiones húmedas como áridas. Mide 18 cm de longitud y pesa en promedio 35 g.\nSu dieta consiste principalmente de frutos, pero también de néctar e insectos.\n\nOTROS NOMBRES\nTángara azulada, azulejo de jardín, azulejo común, tangara azulgrís."
        ,"NOMBRE CIENTÍFICO\nCyanocitta cristata.\n\nDESCRIPCIÓN\nEsta ave se encuentra sobre todo en bosques mixtos, pero también es visible en parques y jardines de algunas ciudades. Como en otras aves azuladas, la coloración del arrendajo azul no deriva de pigmentos, sino que es el resultado de la refracción de la luz debida a la estructura interna de las plumas; si se aplasta una de las plumas la coloración azul desaparece.\nBusca su comida tanto en el suelo como en los árboles, y consume prácticamente todo tipo de alimentos vegetales y animales, tales como bellotas, hayucos, semillas de herbáceas, granos, frutos, bayas, cacahuetes, pan, carne, huevos y polluelos de otras aves, muchos tipos de invertebrados, basura de los parques y alimento para pájaros.\n\nOTROS NOMBRES\narrendajo azul."
        ,"NOMBRE CIENTÍFICO\nRamphastos toco.\n\nDESCRIPCIÓN\nEsta especie se localiza en los bosques húmedos del este de Sudamérica. Suelen tener una longitud media de 63 centímetros, de los cuales el pico ocupa unos 20 cm y alcanzan un peso superior a 500 gramos.\nEl tucán toco se alimenta principalmente de fruta, pero ocasionalmente también come insectos, reptiles, huevos de otras aves y verduras como : zanahoria, tomate y pepino."
        ,"NOMBRE CIENTÍFICO\nRamphastos brevis.\n\nDESCRIPCIÓN\nHabita en selvas húmedas y tierras bajas en donde también puede llegar a ser observada en pastizales con árboles frutales dispersos y en cultivos. Cuando se alimente es común verlo girando la cabeza al revés. También es común verlo bebiendo agua en bromelias y siguiendo hormigas legionarias aprovechando para atrapar presas que se levantan a su paso. Mide de 46 a 48 cm de longitud y pesa entre 365 y 482 g.\nSe alimentan de frutos, hormigas y otros insectos y animales pequeños."};

    public void ChangeInformation(GameObject bird)
    {
        nbird= int.Parse(bird.name);
        map.sprite=maps[nbird];
        photo.sprite=birdPhotos[nbird];
        birdsAnimations.ChangeInfoBirdName(nbird);
        description.text=birdsInformationTextEs[nbird];
        myScrollRect.verticalNormalizedPosition = 1f;
    }

    public void NextBird(int direction)
    {
        if(nbird+direction==birdPhotos.Length)
            nbird=0;
        else if(nbird+direction<0)
            nbird=birdPhotos.Length-1;
        else
            nbird=nbird+direction;

        map.sprite=maps[nbird];
        photo.sprite=birdPhotos[nbird];
        birdsAnimations.ChangeInfoBirdName(nbird);
        description.text=birdsInformationTextEs[nbird];
        myScrollRect.verticalNormalizedPosition = 1f;
    }
}
